# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayo Ayco
author: Ayo Ayco
attribution: "2021 &copy; by Ramon Ayco Jr"
website: ayco.io
email: ramon.aycojr@pm.me
description: >- # this means to ignore newlines until "baseurl:"
    Ayo Ayco is a Software Engineer from The Philippines, now in The Netherlands!
baseurl: "/" # the subpath of your site, e.g. /blog
google_analytics: 'UA-53021803-1'
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ayoayco
github_username:  ayoayco

destination: public
source: src

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: post
    author: Ayo
    excerpt_separator: <!--more-->

# this goes inside _config.yml. Change as required
navigation:
- text: Profile
  newWindow: false
  url: /
- text: Notes
  newWindow: false
  url: /notes/
- text: Talks
  newWindow: false
  url: /talks/
- text: "Music"
  newWindow: true
  url: https://soundcloud.com/ayoayco
- text: "Blog"
  newWindow: true
  url: https://blog.ayco.io



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
